### ISSUE TITLE
ParserError while parsing a block mapping / expected block end but found scalar

### ISSUE THREAD

**Issue by Boston-of-Gilead** [mailchannels/palinurus#3]
This is due to a problem with the YAML, not related to Palinurus. Closing issue.

**Comment by Boston-of-Gilead** [comment]
There seems to be an issue with line 28 of the deployment.yaml.template:

```
PS C:\Users\<user>\Desktop\palinurus-master> python.exe .\palinurus.py --source .\templates
This will convert kubernetes resources to a helm chart
Using .\templates
C:\Users\<user>\Desktop\palinurus-master\palinurus.py:40: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yamlObject = yaml.load(textData)
Traceback (most recent call last):
  File "C:\Users\<user>\Desktop\palinurus-master\palinurus.py", line 117, in <module>
    newchart = Chart(sourceDir)
  File "C:\Users\<user>\Desktop\palinurus-master\palinurus.py", line 40, in __init__
    yamlObject = yaml.load(textData)
  File "C:\Users\<user>\AppData\Roaming\Python\Python310\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\<user>\AppData\Roaming\Python\Python310\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\<user>\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\<user>\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\<user>\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\<user>\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\<user>\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\<user>\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\<user>\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\<user>\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\<user>\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\<user>\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\<user>\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "C:\Users\<user>\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "C:\Users\<user>\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\<user>\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\<user>\AppData\Roaming\Python\Python310\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\<user>\AppData\Roaming\Python\Python310\site-packages\yaml\parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 27, column 11:
            - name: {{ .Chart.Name }}
              ^
expected <block end>, but found '<scalar>'
  in "<unicode string>", line 28, column 76:
     ... "$name" "images" "repository" }}\{{ index .Values "global" "$nam ...
                                         ^
PS C:\Users\<user>\Desktop\palinurus-master>
```

Deployment.yaml.template lines 26-30:

```
      containers:
        - name: {{ .Chart.Name }}
          image: {{ index .Values "global" "$name" "images" "repository" }}\{{ index .Values "global" "$name" "images" "$ccname" "image" }}:{{ index .Values "global" "$name" "images" "$ccname" "tag" }}
          imagePullPolicy: {{ index .Values "global" "$name" "images" "pullPolicy" }}
```

Exactly which files should be in the source directory? 

Thanks :)

**Comment by Boston-of-Gilead** [comment]
Resolved. I made a separate directory as the source directory, and pointed the Palinurus script at that; then I made some adjustments to the Palinurus script to match my existing deployment.yaml's structure (on lines 78 and 79 I swapped ["requests"] for ["limits"].
